# Generated by Django 2.2.12 on 2020-04-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tyres', models.CharField(max_length=50)),
                ('total_weight', models.CharField(max_length=50)),
                ('chain', models.CharField(max_length=50)),
                ('fork', models.CharField(max_length=50)),
                ('pedals', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=50)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikesshop.Colour')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikesshop.Frame')),
            ],
        ),
    ]
